### ISSUE TITLE
Speedhack

### ISSUE THREAD

**Issue by ExtremeMen** [TheReVeaLz/TurnAnimeGame-Release#3]
Please fix the speedhack in battle 💀 , the speed not sync in game (10 speed)

**Comment by TheReVeaLz** [comment]
I guess I don't need to fix that since the main purposes from speedhack is to end the match asap

**Comment by ExtremeMen** [comment]
How about in

Talk speed
Menu (fast refine,lvl up,etc.)
Video cutscenes (not the main cutscenes)

I use the old cheat before the update 1.1

**Comment by ExtremeMen** [comment]
![IMG_20230616_052713](https://github.com/TheReVeaLz/TurnAnimeGame-Release/assets/136742815/fa1d0f56-abe0-474d-9d34-f319427f3766)
This one I use before the update (no glitch/delay animation in speedhack [10])

**Comment by TheReVeaLz** [comment]
Actually current speedhack didn't affect to dialogue. The one affected with this is just exploring movement and battle phase

**Comment by ExtremeMen** [comment]
Oh ok .. and still thanks for the cheat :)
